services:
  - type: web
    name: ai-interview-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn render:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyCIhzKAOCeRUL-GX2q0jbJL6-vgxUMPIeM
      - key: DATABASE_URL
        value: postgresql://ai_interview_belk_user:kGG0EDxGMQl9IJv01tNepkoB0NZSBViS@dpg-d1iakeur433s73a95iag-a.oregon-postgres.render.com/ai_interview_belk
